spring.application.name=traveldiary

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=local

mybatis.type-aliases-package=com.td.traveldiary.domain.**.entity
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
